/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/
public class ProblemTwo {

	public static void main(String[] args) {
	     int prevVal = 1;
	     int prevPrevVal = 0;
	     int currVal=0;
	     int count=0;
	     int range=4000000;
	     do{
	         currVal = prevVal + prevPrevVal;
	         prevPrevVal = prevVal;
	         prevVal = currVal;
	         //System.out.print(currVal+", ");
	         if (currVal%2==0)
	         {
	         count=count+currVal;
	         }
	     }while(currVal<range);//n is the number of terms
	     System.out.print("The sum of the even terms in the fibonacci sequence below "+range+" is: "+count);
	}

}
